version: "3"
services:
  alc-mobile-api:
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - DB_PROTOCOL=tcp(host:port)
      - OAUTH_CLIENT_ID=
      - OAUTH_CLIENT_SECRET=
