version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    volumes:
      - .dev_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alc_root_pw
      MYSQL_DATABASE: alc_mobile
      MYSQL_USER: alc_mobile_user
      MYSQL_PASSWORD: alc_password
  server:
    depends_on:
      - db
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - BASE_URL=http://localhost:8080
      - DB_DSN=alc_mobile_user:alc_password@tcp(db:3306)/alc_mobile
      - OAUTH_CLIENT_ID=
      - OAUTH_CLIENT_SECRET=
      - DEFAULT_CONFERENCE_ID=1
      - S3_REGION=us-west-2
      - S3_BUCKET=
      - S3_AUTH_ID=
      - S3_SECRET=
